"""'pydicio'

Revision ID: 261867b87ab8
Revises: 
Create Date: 2024-04-14 19:14:11.209816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261867b87ab8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pydicio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Word ID'),
    sa.Column('word', sa.String(), nullable=True, comment='Word'),
    sa.Column('length', sa.Integer(), nullable=True, comment='Length of the word'),
    sa.PrimaryKeyConstraint('id'),
    info={'description': 'Created to store all data from Dicio.com.br related to brazilian portuguese words'}
    )
    op.create_index(op.f('ix_pydicio_id'), 'pydicio', ['id'], unique=False)
    op.create_index(op.f('ix_pydicio_length'), 'pydicio', ['length'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pydicio_length'), table_name='pydicio')
    op.drop_index(op.f('ix_pydicio_id'), table_name='pydicio')
    op.drop_table('pydicio')
    # ### end Alembic commands ###
