"""'main'

Revision ID: 1ce99d5fa5af
Revises: 
Create Date: 2024-10-22 17:46:46.312980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce99d5fa5af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Champion Id'),
    sa.Column('key', sa.Integer(), nullable=True, comment='Champion Id'),
    sa.Column('name', sa.String(), nullable=True, comment='Champion name'),
    sa.Column('tags', sa.String(), nullable=True, comment='Champion tags'),
    sa.Column('attack', sa.Integer(), nullable=True, comment='Champion attack value'),
    sa.Column('defense', sa.Integer(), nullable=True, comment='Champion defense value'),
    sa.Column('magic', sa.Integer(), nullable=True, comment='Champion magic value'),
    sa.Column('difficulty', sa.Integer(), nullable=True, comment='Champion difficulty value'),
    sa.Column('hp', sa.Float(), nullable=True, comment='Champion hp value'),
    sa.Column('hpperlevel', sa.Float(), nullable=True, comment='Champion hpperlevel value'),
    sa.Column('mp', sa.Float(), nullable=True, comment='Champion mp value'),
    sa.Column('mpperlevel', sa.Float(), nullable=True, comment='Champion mpperlevel value'),
    sa.Column('movespeed', sa.Float(), nullable=True, comment='Champion movespeed value'),
    sa.Column('armor', sa.Float(), nullable=True, comment='Champion armor value'),
    sa.Column('armorperlevel', sa.Float(), nullable=True, comment='Champion armorperlevel value'),
    sa.Column('spellblock', sa.Float(), nullable=True, comment='Champion spellblock value'),
    sa.Column('spellblockperlevel', sa.Float(), nullable=True, comment='Champion spellblockperlevel value'),
    sa.Column('attackrange', sa.Float(), nullable=True, comment='Champion attackrange value'),
    sa.Column('hpregen', sa.Float(), nullable=True, comment='Champion hpregen value'),
    sa.Column('hpregenperlevel', sa.Float(), nullable=True, comment='Champion hpregenperlevel value'),
    sa.Column('mpregen', sa.Float(), nullable=True, comment='Champion mpregen value'),
    sa.Column('mpregenperlevel', sa.Float(), nullable=True, comment='Champion mpregenperlevel value'),
    sa.Column('crit', sa.Float(), nullable=True, comment='Champion crit value'),
    sa.Column('critperlevel', sa.Float(), nullable=True, comment='Champion critperlevel value'),
    sa.Column('attackdamage', sa.Float(), nullable=True, comment='Champion attackdamage value'),
    sa.Column('attackdamageperlevel', sa.Float(), nullable=True, comment='Champion attackdamageperlevel value'),
    sa.Column('attackspeedperlevel', sa.Float(), nullable=True, comment='Champion attackspeedperlevel value'),
    sa.Column('attackspeed', sa.Float(), nullable=True, comment='Champion attackspeed value'),
    sa.Column('png_path', sa.String(), nullable=True, comment='Path to png'),
    sa.PrimaryKeyConstraint('id'),
    info={'description': 'Created to store all data about League Of Legends champions'}
    )
    op.create_index(op.f('ix_champions_id'), 'champions', ['id'], unique=False)
    op.create_index(op.f('ix_champions_name'), 'champions', ['name'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Float(), nullable=False, comment='Item Id'),
    sa.Column('name', sa.String(), nullable=True, comment='Item name'),
    sa.Column('tags', sa.String(), nullable=True, comment='Item tags'),
    sa.Column('gold_value', sa.Float(), nullable=True, comment='Item value'),
    sa.Column('purchasable', sa.Boolean(), nullable=True, comment='Bool that indicates if the item is purchasable'),
    sa.Column('png_path', sa.String(), nullable=True, comment='Path to png'),
    sa.PrimaryKeyConstraint('id'),
    info={'description': 'Created to store all data about items'}
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_champions_name'), table_name='champions')
    op.drop_index(op.f('ix_champions_id'), table_name='champions')
    op.drop_table('champions')
    # ### end Alembic commands ###
